# Generated by Django 3.2.20 on 2023-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.CharField(default='https://placekitten.com/200/300', max_length=100),
        ),
    ]
